
const app=document.querySelector('#app');
let state=JSON.parse(localStorage.getItem('mycycle-pro-v1')||'{"periods":[],"logs":{}}');
if(!Array.isArray(state.periods)) state.periods=[];
const monthColors=['#ee4e98','#ef6e78','#efa447','#4fba72','#9ec84c','#45b7aa','#3da4dd','#7b1e87','#9c6bd5','#dd5aa1','#6f79c9','#ed755e'];
document.documentElement.style.setProperty('--accent',monthColors[new Date().getMonth()]);
const save=()=>localStorage.setItem('mycycle-pro-v1',JSON.stringify(state));
const today=new Date();
function iso(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function sorted(){return [...state.periods].sort((a,b)=>a.start.localeCompare(b.start))}
function days(a,b){return Math.round((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000)}
function avgCycle(){let p=sorted();if(p.length<2)return 28;let a=[];for(let i=1;i<p.length;i++){let n=days(p[i-1].start,p[i].start);if(n>=15&&n<=60)a.push(n)}return a.length?Math.round(a.reduce((x,y)=>x+y,0)/a.length):28}
function avgPeriod(){let a=sorted().filter(x=>x.end).map(x=>days(x.start,x.end)+1).filter(x=>x>0&&x<16);return a.length?Math.round(a.reduce((x,y)=>x+y,0)/a.length):5}
function latest(){let p=sorted();return p[p.length-1]||null}
function cycleDay(){let l=latest();return l?Math.max(1,days(l.start,iso(today))+1):'—'}
function phase(){let d=Number(cycleDay());if(!d)return 'Start tracking';if(d<=5)return 'Menstrual phase';let o=avgCycle()-14;if(d<o)return 'Follicular phase';if(Math.abs(d-o)<=1)return 'Estimated ovulation';return 'Luteal phase'}
function nextPeriod(){let l=latest();if(!l)return null;let d=new Date(l.start+'T12:00:00');d.setDate(d.getDate()+avgCycle());return iso(d)}
function nextIn(){let np=nextPeriod();return np?Math.max(0,days(iso(today),np)):null}
function dateStrip(){let h='';for(let i=-3;i<=3;i++){let d=new Date(today);d.setDate(today.getDate()+i);h+=`<div class="date ${i===0?'today':''}">${d.toLocaleDateString('en',{weekday:'short'})}<b>${d.getDate()}</b></div>`}return h}
function home(){app.innerHTML=`<div class="greet"><h2>Good ${today.getHours()<12?'morning':today.getHours()<18?'afternoon':'evening'}! 🌸</h2><div class=sub>Your body is doing amazing.</div></div><div class=date-strip>${dateStrip()}</div>
<section class=hero><img src="assets/home-art.png"><div class=cycle-card><div>Cycle day</div><strong>${cycleDay()}</strong><div class=phase>${phase()} ⓘ</div><div class=progress><i></i></div></div>
<div class=prediction>🌼 ${latest()?'Next period in':'Smart predictions'} <strong>${latest()?nextIn()+' days':'Start tracking'}</strong><br><small>${latest()?'Based on your logged cycle history':'Log a period to begin predictions'}</small></div>
<div class=quick3><div class=tile onclick=openPeriod()><span>🩸</span>Log period</div><div class=tile onclick="go('symptoms')"><span>🌸</span>Log symptoms</div><div class=tile onclick="go('mood')"><span>🙂</span>Log mood</div></div></section>
<div class=section-title>Today's insights</div><div class=insight><h3>☀️ Your energy may be changing today!</h3><p>Track how you feel to discover patterns that are personal to you.</p><div class=flower>🌷</div></div>
<div class=section-title>Quick tips</div><div class=tip>💧 Stay hydrated</div><div class=tip>🧘‍♀️ Light exercise</div><div class=tip>🥗 Eat iron-rich foods</div><div class=note>Theme accent changes automatically every month ✨</div>`}
function calendar(){let y=today.getFullYear(),m=today.getMonth(),first=new Date(y,m,1).getDay(),count=new Date(y,m+1,0).getDate(),g='SMTWTFS'.split('').map(x=>`<div class=dow>${x}</div>`).join('');for(let i=0;i<first;i++)g+='<div></div>';for(let d=1;d<=count;d++){let ds=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;let c=d===today.getDate()?'today':'';state.periods.forEach(p=>{if(p.start&&p.end&&ds>=p.start&&ds<=p.end)c='period'});g+=`<div class="cell ${c}">${d}</div>`}app.innerHTML=`<div class=calendar-head><div class=page-title>Calendar</div><b>${today.toLocaleDateString('en',{month:'long',year:'numeric'})}</b></div><div class="card cal"><div class=grid>${g}</div><div class=legend>● Period　🟢 Fertile window　🟣 Ovulation　• Logged</div></div><div class="card summary">🗓️ <b>Period ${latest()?'in '+nextIn()+' days':'not predicted yet'}</b><br><small>Average cycle ${avgCycle()} days • calculated automatically</small></div>`}
const logItems=[['🩸','Period'],['🌸','Symptoms'],['🙂','Mood'],['🌙','Sleep'],['❤️','Sex'],['⚖️','Weight'],['🥤','Water'],['✏️','Notes']];
function log(){app.innerHTML=`<div class=page-title>Log today</div><div class=sub>${today.toLocaleDateString('en',{weekday:'short',month:'short',day:'numeric'})}</div><div class=section-title>What would you like to log?</div><div class=loggrid>${logItems.map(x=>`<div class="card logtile" onclick="${x[1]==='Period'?'openPeriod()':x[1]==='Symptoms'?`go('symptoms')`:x[1]==='Mood'?`go('mood')`:`quick('${x[1]}')`}"><span>${x[0]}</span>${x[1]}</div>`).join('')}</div><textarea id=note placeholder="Add a note… (optional)"></textarea><button class=save onclick=saveNote()>Save</button>`}
function insights(){app.innerHTML=`<div class=page-title>Insights</div><div class=tabs><button class=on>Cycle</button><button onclick="go('symptoms')">Symptoms</button><button onclick="go('mood')">Mood</button></div><div class="card metric">Cycle length<strong>${avgCycle()} days</strong><small>Average from your logged cycles</small><div class=chart>${[45,72,54,80,87,65].map(v=>`<i class=bar style="height:${v}%"></i>`).join('')}</div></div><div class=stats><div class="card stat">Period length<strong>${avgPeriod()} days</strong></div><div class="card stat">Ovulation day<strong>Day ${Math.max(1,avgCycle()-14)}</strong></div></div><div class=section-title>Your patterns</div><div class="card metric">Bloating　●●●○○<br><br>Headache　●●○○○<br><br>Mood swings　●●●○○</div>`}
function symptoms(){let s=[['🌸','Bloating'],['🔥','Cramps'],['🧊','Headache'],['🌺','Acne'],['🩸','Breast tenderness'],['🧘‍♀️','Back pain']];app.innerHTML=`<div class=page-title>Symptoms</div><div class=tabs><button class=on>This cycle</button><button>History</button></div>${s.map(x=>`<div class="card symrow"><span>${x[0]} ${x[1]}</span><span onclick="quick('${x[1]}')">●●○　›</span></div>`).join('')}<button class=save onclick="quick('Custom symptom')">＋ Add symptom</button>`}
function mood(){app.innerHTML=`<div class=page-title>Mood</div><div class="card moodbars">${[65,88,55,72,91,60,78].map(v=>`<i style="--h:${v}%"></i>`).join('')}</div><div class=section-title>How are you feeling today?</div><div class=moods>${['🥰 Amazing','🙂 Good','😌 Okay','😔 Sad','😟 Anxious','😤 Irritable'].map(x=>`<div class="card mood" onclick="quick('${x}')">${x}</div>`).join('')}</div><div class=quote>🌷 Small steps, big smiles! 💜</div>`}
function profile(){let p=sorted().slice().reverse();app.innerHTML=`<div class=profile><div class=avatar>👩🏻</div><div class=page-title>MyCycle 💜</div><div class=sub>Listening to my body.</div><div class=quote>🌿 “Every cycle is unique, and so are you.” 🌸</div></div><div class=menu><div class="card row">📊 My data <span>›</span></div><div class="card row">🔔 Reminders <span>›</span></div><div class="card row">☁️ Backup & Sync <span>›</span></div><div class="card row">🔐 Passcode / Face ID <span>›</span></div><div class="card row">🎨 Theme <span>Auto ›</span></div><div class="card row">ⓘ About <span>›</span></div></div><div class=section-title>Period history</div>${p.length?p.map(x=>`<div class="card history">${x.start} → ${x.end}<button onclick="editPeriod('${x.start}')">Edit</button></div>`).join(''):'<div class="card history">No periods logged yet.</div>'}<div class=note>Cycle length and period length are calculated automatically from your period history.</div>`}
function openPeriod(editStart=null){let p=editStart?state.periods.find(x=>x.start===editStart):{start:iso(today),end:iso(today)};document.body.insertAdjacentHTML('beforeend',`<div class=modal id=modal><div class=sheet><h2>${editStart?'Edit':'Log'} period 🩸</h2><label>Start date</label><input id=ps type=date value="${p.start}"><label>End date</label><input id=pe type=date value="${p.end}"><button class=save onclick="savePeriod('${editStart||''}')">Save period</button><p style="text-align:center" onclick=modal.remove()>Cancel</p></div></div>`)}
function savePeriod(editStart){let p={start:ps.value,end:pe.value};if(!p.start||!p.end)return alert('Choose both dates');if(p.end<p.start)return alert('End date must be after start date');if(editStart){let i=state.periods.findIndex(x=>x.start===editStart);state.periods[i]=p}else state.periods.push(p);save();modal.remove();go('calendar')}
function editPeriod(start){openPeriod(start)}
function quick(x){state.logs[x]=(state.logs[x]||0)+1;save();alert(x+' logged 💜')}
function saveNote(){state.logs.note=document.querySelector('#note').value;save();alert('Saved 💜')}
function go(page){({home,calendar,log,insights,symptoms,mood,profile}[page]||home)();document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page))}
document.querySelectorAll('.bottom-nav button[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));
go('home');
if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js');
